# Generated by Django 4.2.3 on 2023-07-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='is_published',
            new_name='published',
        ),
    ]
